### ISSUE TITLE
InvalidLocationConstraint error when using kilt installer for location aws us-east-1

### ISSUE THREAD

**Issue by balinaveen** [falcosecurity/kilt#23]
**Summary**
Unable to use kilt installer to create Kilt Macro in aws us-east-1 location

**How to reproduce it**
$ ./kilt-cfn-installer-linux  -r us-east-1 MyMacro  ./falco.kilt.cfg
Getting AWS account and region...059797578166 in us-east-1
Getting S3 bucket...ERROR:root:An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid

**Expected behaviour**
MyMacro should be created and available in AWS CloudFormation when the above command is executed

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel:
$ uname -a
Linux naveen-ubuntu-VirtualBox 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:

**Additional context**
This may be related to https://github.com/boto/boto3/issues/125 and likely caused by this change in kilt https://github.com/falcosecurity/kilt/pull/21/files

**Comment by admiral0** [comment]
should be fixed in v0.2.0
